### ISSUE TITLE
Watch seems to stop working after some time 

### ISSUE THREAD

**Issue by meyskens** [src-d/kubernetes-local-pv-provisioner#6]
While working on https://github.com/src-d/infrastructure/issues/290 we discovered that the path did not get created correctly. There were no logs.
When restarting the pod it found the PV and did it's job.

I suspect I overlooked a watch error either caused by
* time constraint
* our k8s API server's VIP changing to another controller

**Comment by meyskens** [comment]
From looking at my past work with watchers (that i run in production for almost a year) I strongly suspect the VIP change to be causing this. (or some other factor)

**Comment by meyskens** [comment]
I found out the operator has no issues so I totally suspect that i made a mistake here.

**Comment by meyskens** [comment]
I re-wrote the watcher to use a Informer (helper) instead: https://github.com/src-d/kubernetes-local-pv-provisioner/pull/7

**Comment by driosalido** [comment]
The code looks good to me, but I prefer @rporres to take a look as my go is still very "green".

**Comment by meyskens** [comment]
@driosalido no problem! I would also prefer to keep the ticket open till we confirm it doesn't happen again. All I did here was using a newer helper instead of calling `Watch()` in the code.

**Comment by rporres** [comment]
Looks good. Reading the informer code it performs the watch itself https://github.com/kubernetes/client-go/blob/master/informers/core/v1/persistentvolume.go. Let's give it a try! 🎉

**Comment by meyskens** [comment]
Informers are also what the postgres-operator uses, and I am sure that one works ;)

**Comment by rporres** [comment]
Merged #7 and created `v1.0.1`

**Comment by rporres** [comment]
Testing this in `ml` cluster

**Comment by rporres** [comment]
works great!
