### ISSUE TITLE
Thanks and a question

### ISSUE THREAD

**Issue by schafdog** [src-d/kubernetes-local-pv-provisioner#8]
Been looking for something like this for a while, so thanks for sharing!

Still a newbie, so this is prob. OT. Is there a way to name the daemonset so the hostname is included?

**Comment by meyskens** [comment]
I'm afraid that is not possible in Kubernetes, depending on your setup you can try an alternative like static pods: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#alternatives-to-daemonset
